# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'

target 'ListAppGrability' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ListAppGrability
pod 'Alamofire', '~> 3.5.0'
pod 'ObjectMapper', '~> 2.0'

end
